# .github/workflows/deploy.yml
name: Build, Push Docker (Prune) & Deploy to K8s

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: 'gateway'
            path: 'gateway'
            image: 'doseza007/nest-gateway'
          - name: 'user-service'
            path: 'user'
            image: 'doseza007/nest-user'
          - name: 'product-service'
            path: 'product'
            image: 'doseza007/nest-product'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prune monorepo for ${{ matrix.service.name }}
        run: pnpm turbo prune ${{ matrix.service.name }} --docker

      - name: Copy custom Dockerfile to pruned output
        run: cp dockerfile.bun out/Dockerfile

      - name: Get build info
        id: info
        run: |
          echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push from pruned output
        uses: docker/build-push-action@v5
        with:
          context: ./out
          file: ./out/Dockerfile
          push: true
          build-args: |
            PROJECT_NAME=${{ matrix.service.name }}
            PROJECT_PATH=${{ matrix.service.path }}
          tags: |
            ${{ matrix.service.image }}:latest
            ${{ matrix.service.image }}:${{ github.ref_name }}
            ${{ matrix.service.image }}:${{ steps.info.outputs.DATE }}-${{ steps.info.outputs.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

