# .github/workflows/deploy.yml
name: Build, Push Docker (Hybrid) & Deploy to K8s

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: 'gateway'
            path: 'gateway'
            image: 'doseza007/nest-gateway'
          - name: 'user-service'
            path: 'user'
            image: 'doseza007/nest-user'
          - name: 'product-service'
            path: 'product'
            image: 'doseza007/nest-product'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get build info
        id: info
        run: |
          echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push with Hybrid (pnpm+bun)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile.bun
          push: true
          build-args: |
            PROJECT_NAME=${{ matrix.service.name }}
            PROJECT_PATH=${{ matrix.service.path }}
          tags: |
            ${{ matrix.service.image }}:latest
            ${{ matrix.service.image }}:${{ github.ref_name }}
            ${{ matrix.service.image }}:${{ steps.info.outputs.DATE }}-${{ steps.info.outputs.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key & Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "--- Deploying all services with new release tag: ${{ github.ref_name }} ---"
            
            kubectl set image deployment/gateway gateway=doseza007/nest-gateway:${{ github.ref_name }} --namespace your-namespace
            kubectl set image deployment/user user=doseza007/nest-user:${{ github.ref_name }} --namespace your-namespace
            kubectl set image deployment/product product=doseza007/nest-product:${{ github.ref_name }} --namespace your-namespace

            echo "--- Waiting for rollout to complete ---"
            kubectl rollout status deployment/gateway --namespace your-namespace
            kubectl rollout status deployment/user --namespace your-namespace
            kubectl rollout status deployment/product --namespace your-namespace

            echo "--- Deployment finished successfully! ---"