name: Build, Push Docker and Deploy to Kubernetes

on:
  release:
    types: [published]

jobs:
  build-and-push-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Docker Hub Credentials (DANGER: REMOVE THIS STEP AFTER DEBUGGING!)
        env:
          DOCKER_USERNAME_ENV: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD_ENV: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "--- DEBUGGING CREDENTIALS (DO NOT COMMIT THIS!) ---"
          echo "DOCKER_USERNAME: $DOCKER_USERNAME_ENV"
          # หากคุณต้องการให้แสดง Password จริงๆ ซึ่งไม่แนะนำอย่างยิ่ง ให้เปิดคอมเมนต์บรรทัดข้างล่างนี้
          # echo "DOCKER_PASSWORD: $DOCKER_PASSWORD_ENV"
          echo "---------------------------------------------------"


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          push: true
          tags: doseza007/nest-gateway:latest

  build-and-push-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Docker Hub Credentials (DANGER: REMOVE THIS STEP AFTER DEBUGGING!)
        env:
          DOCKER_USERNAME_ENV: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD_ENV: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "--- DEBUGGING CREDENTIALS (DO NOT COMMIT THIS!) ---"
          echo "DOCKER_USERNAME: $DOCKER_USERNAME_ENV"
          # หากคุณต้องการให้แสดง Password จริงๆ ซึ่งไม่แนะนำอย่างยิ่ง ให้เปิดคอมเมนต์บรรทัดข้างล่างนี้
          # echo "DOCKER_PASSWORD: $DOCKER_PASSWORD_ENV"
          echo "---------------------------------------------------"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user image
        uses: docker/build-push-action@v5
        with:
          context: ./user
          push: true
          tags: doseza007/nest-user:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: [build-and-push-gateway, build-and-push-user]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug SSH Credentials (DANGER: REMOVE THIS STEP AFTER DEBUGGING!)
        env:
          SERVER_HOST_ENV: ${{ secrets.SERVER_HOST }}
          SSH_PASSWORD_ENV: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "--- DEBUGGING SSH CREDENTIALS (DO NOT COMMIT THIS!) ---"
          echo "SERVER_HOST: $SERVER_HOST_ENV"
          # หากคุณต้องการให้แสดง Password จริงๆ ซึ่งไม่แนะนำอย่างยิ่ง ให้เปิดคอมเมนต์บรรทัดข้างล่างนี้
          # echo "SSH_PASSWORD: $SSH_PASSWORD_ENV"
          echo "---------------------------------------------------"

      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: 'root'
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/ne
            kubectl apply -f c.yaml