name: Print Known GitHub Secrets

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Unsafe: Print selected secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}"
          echo "SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}"
